import React from "react";
import Header from "@/app/header"; 
import Footer from "@/app/footer";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/app/components/ui/Card";
import { Badge } from "@/app/components/ui/Badge";
import { Progress } from "@/app/components/ui/Progress";
import singalsModel from "@/app/models/signalsModel"; 
import Icon from "@/app/components/Icon";
import {connectDB} from "@/app/db";
import Image from "next/image";
import Disclaimer from "@/app/components/Disclaimer";
import { getCryptoLogo } from "@/utils/utils";



async function getSignals() {
  await connectDB();
  const signals = await singalsModel
    .find({ status: { $in: ["pending", "triggered", "closed"] } })
    .sort({ createdAt: -1 })
    .limit(6)
    .lean();

  const signalsWithLogos = await Promise.all(
    signals.map(async (signal) => {
      const logo = await getCryptoLogo(signal.symbol);
      return { ...signal, logo };
    })
  );

  return signalsWithLogos;
}

function SignalStatusBadge({ status, profit }: { status: string, profit?: number }) {
  const variants: any = {
    pending: { 
      label: "Active", 
      color: "bg-blue-500/20 text-blue-400 border-blue-500/30 dark:bg-blue-500/20 dark:text-blue-400",
      icon: <Icon icon="fa-solid:bolt" className="text-xs" />
    },
    triggered: { 
      label: "Triggered", 
      color: "bg-purple-500/20 text-purple-600 border-purple-500/30 dark:bg-purple-500/20 dark:text-purple-400",
      icon: <Icon icon="fa-solid:chart-line" className="text-xs" />
    },
    closed: profit && profit > 0 ? { 
      label: `+${profit}%`, 
      color: "bg-emerald-500/20 text-emerald-600 border-emerald-500/30 dark:bg-emerald-500/20 dark:text-emerald-400",
      icon: <Icon icon="fa-solid:money-bill-trend-up" className="text-xs" />
    } : { 
      label: "Closed", 
      color: "bg-gray-500/20 text-gray-600 border-gray-500/30 dark:bg-gray-500/20 dark:text-gray-400",
      icon: <Icon icon="fa-solid:clock" className="text-xs" />
    }
  };

  const config = variants[status] || variants.closed;
  
  return (
    <Badge 
      variant="outline" 
      className={`${config.color} border backdrop-blur-sm flex items-center gap-1.5 px-3 py-1.5 rounded-full`}
    >
      {config.icon}
      <span className="font-semibold">{config.label}</span>
    </Badge>
  );
}

export default async function FreeSignalsPage() {
  const signals = await getSignals();

  const activeSignals = signals.filter((s: any) => s.status !== "closed");
  const closedSignals = signals.filter((s: any) => s.status === "closed");

  const profitableClosed = closedSignals.filter((s: any) => s.tpHitCount > 0);
  const winRate = closedSignals.length > 0 
    ? Math.round((profitableClosed.length / closedSignals.length) * 100) 
    : 0;

  return (
    <div className="flex min-h-screen flex-col bg-gradient-to-br from-background via-base-200 to-background text-foreground dark:from-dark-950 dark:via-dark-900 dark:to-dark-950">
      <Header />

      <main className="flex-1 py-12 px-4 md:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
         
          <div className="text-center mb-16 relative">
        
           
            
            <div className="relative">
              <Badge className="mb-6 px-4 py-2 bg-gradient-primary text-primary-content border-0 animate-pulse-red">
                <Icon icon="fa-solid:fire" className="mr-2 animate-pulse" /> LIVE TRADING SIGNALS
              </Badge>
              
              <h1 className="text-5xl md:text-7xl font-bold mb-8 bg-gradient-to-r from-primary via-red-400 to-orange-400 bg-clip-text text-transparent">
                AI-Powered <span className="block mt-2">Trading Signals</span>
              </h1>
              
              <p className="text-xl text-muted-foreground max-w-3xl mx-auto mb-10 leading-relaxed dark:text-gray-300">
                Real-time signals generated by advanced machine learning algorithms. 
                High accuracy trading opportunities delivered every 8 hours.
              </p>

         
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-2xl mx-auto mb-8">
                <div className="bg-card backdrop-blur-sm rounded-2xl p-4 border border-border dark:bg-dark-800/50 dark:border-dark-700">
                  <div className="text-3xl font-bold text-primary">{activeSignals.length}</div>
                  <div className="text-sm text-muted-foreground">Active Signals</div>
                </div>
                <div className="bg-card backdrop-blur-sm rounded-2xl p-4 border border-border dark:bg-dark-800/50 dark:border-dark-700">
                  <div className="text-3xl font-bold text-emerald-600 dark:text-emerald-400">{winRate}%</div>
                  <div className="text-sm text-muted-foreground">Win Rate</div>
                </div>
                <div className="bg-card backdrop-blur-sm rounded-2xl p-4 border border-border dark:bg-dark-800/50 dark:border-dark-700">
                  <div className="text-3xl font-bold text-purple-600 dark:text-purple-400">24/7</div>
                  <div className="text-sm text-muted-foreground">Monitoring</div>
                </div>
                <div className="bg-card backdrop-blur-sm rounded-2xl p-4 border border-border dark:bg-dark-800/50 dark:border-dark-700">
                  <div className="text-3xl font-bold text-amber-600 dark:text-amber-400">AI</div>
                  <div className="text-sm text-muted-foreground">Powered</div>
                </div>
              </div>

              <div className="flex flex-wrap gap-3 justify-center">
                <Badge variant="secondary" className="text-base px-5 py-2.5 ">
                  <Icon icon="fa-solid:coins" className="mr-2 text-primary" /> Multi-Exchange
                </Badge>
                <Badge variant="secondary" className="text-base px-5 py-2.5">
                  <Icon icon="fa-solid:percentage" className="mr-2 text-primary" /> High Accuracy
                </Badge>
                <Badge variant="secondary" className="text-base px-5 py-2.5">
                  <Icon icon="fa-solid:crown" className="mr-2 text-primary" /> Premium Analysis
                </Badge>
              </div>
            </div>
          </div>
          
          <div className="divider" />
          
       
          {activeSignals.length === 0 ? (
            <Card className="bg-card backdrop-blur-sm border-border dark:bg-dark-800/50 dark:border-dark-700">
              <CardContent className="text-center py-16">
                <div className="text-6xl mb-4">📈</div>
                <p className="text-xl text-muted-foreground mb-2 dark:text-gray-300">
                  No active signals at the moment
                </p>
                <p className="text-muted-foreground dark:text-gray-500">
                  Our AI is analyzing the markets. Check back soon!
                </p>
              </CardContent>
            </Card>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {activeSignals.map((signal: any) => (
                <Card 
                  key={signal.signalId} 
                  className="group bg-gradient-to-br from-card to-background border-border 
                           dark:from-dark-800/80 dark:to-dark-900/80 dark:border-dark-700 
                           hover:border-primary/50 hover:shadow-2xl hover:shadow-primary/10 
                           transition-all duration-300 overflow-hidden"
                >
            
                  <div className="absolute inset-0 bg-gradient-to-r from-primary/0 via-primary/5 to-primary/0 
                                -translate-x-full group-hover:translate-x-full transition-transform duration-1000
                                dark:block hidden"></div>
                  
                  <CardHeader className="pb-4 relative">
                    <div className="flex justify-between items-start">
                      <div className="flex items-center gap-4">

                        {signal.logo ? (
                          <div className="relative w-12 h-12 rounded-xl bg-base-200 p-2 border border-border 
                                        dark:bg-dark-700 dark:border-dark-600">
                            <Image
                              src={signal.logo}
                              alt={signal.symbol}
                              width={40}
                              height={40}
                              className="rounded-lg"
                              unoptimized={false}
                            />
                          </div>
                        ) : (
                          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-base-200 to-base-100 border border-border 
                                        dark:from-dark-700 dark:to-dark-800 dark:border-dark-600 
                                        flex items-center justify-center">
                            <Icon icon="fa-solid:coins" className="text-2xl text-muted-foreground dark:text-gray-400" />
                          </div>
                        )}
                        
                        <div>
                          <CardTitle className="text-2xl flex items-center gap-3">
                            <span className="font-bold text-foreground dark:text-white">{signal.symbol}</span>
                            <Badge 
                              variant={signal.signal === "buy" ? "default" : "destructive"}
                              className={`${signal.signal === "buy" 
                                ? 'bg-gradient-to-r from-emerald-500 to-emerald-600 text-emerald-50' 
                                : 'bg-gradient-to-r from-red-500 to-red-600 text-red-50'} 
                                border-0 px-4 py-1.5 rounded-full`}
                            >
                              {signal.signal === "buy" ? (
                                <><Icon icon="fa-solid:arrow-up" className="mr-1" /> STRONG BUY</>
                              ) : (
                                <><Icon icon="fa-solid:arrow-down" className="mr-1" /> STRONG SELL</>
                              )}
                            </Badge>
                          </CardTitle>
                          <CardDescription className="mt-2 flex items-center gap-3 text-muted-foreground dark:text-gray-400">
                            <span className="bg-base-200 px-3 py-1 rounded-lg text-sm dark:bg-dark-700">
                              {signal.exchange}
                            </span>
                            <span>•</span>
                            <span>{signal.timeframe}</span>
                          </CardDescription>
                        </div>
                      </div>
                      
                      <SignalStatusBadge status={signal.status} />
                    </div>
                  </CardHeader>

                  <CardContent className="pt-6 relative">
               
                    <div className="mb-6">
                      <div className="flex justify-between items-center mb-2">
                          <span className="text-sm text-muted-foreground flex items-center gap-2 dark:text-gray-400">
                          <Icon icon="fa-solid:percentage" className="" /> AI Confidence
                        </span>
                        <span className="text-2xl font-bold bg-gradient-to-r from-primary to-orange-400 bg-clip-text text-transparent">
                          {signal.confidence}%
                        </span>
                      </div>
                      <Progress 
                        value={signal.confidence} 
                        className="h-2 bg-base-200 dark:bg-dark-700 
                                 [&>div]:bg-gradient-to-r [&>div]:from-primary [&>div]:to-orange-400"
                      />
                    </div>

                    <div className="grid grid-cols-2 gap-6">
                   
                      <div className="bg-base-100 rounded-xl p-4 border border-border 
                                    dark:bg-dark-800/50 dark:border-dark-700">
                          <p className="text-sm text-muted-foreground flex items-center gap-2 mb-3 dark:text-gray-400">
                          <Icon icon="tabler:target-arrow" className="text-emerald-600 dark:text-emerald-400" /> Take Profit
                        </p>
                        <div className="space-y-2">
                          {signal.takeProfit?.map((tp: number, i: number) => (
                            <div key={i} className="flex justify-between items-center">
                              <span className="text-foreground/80 dark:text-gray-300">TP{i + 1}</span>
                              <span className="font-bold text-emerald-600 dark:text-emerald-400">{tp}</span>
                            </div>
                          ))}
                        </div>
                      </div>

             
                      <div className="bg-base-100 rounded-xl p-4 border border-border 
                                    dark:bg-dark-800/50 dark:border-dark-700">
                        <p className="text-sm text-muted-foreground flex items-center gap-2 mb-3 dark:text-gray-400">
                          <Icon icon="fa-solid:shield-alt" className="text-red-600 dark:text-red-400" /> Stop Loss
                        </p>
                        <p className="text-2xl font-bold text-red-600 dark:text-red-400">{signal.stopLoss || "N/A"}</p>
                        <p className="text-xs text-muted-foreground mt-1 dark:text-gray-500">Risk Management</p>
                      </div>
                    </div>

                
                    <div className="mt-6 pt-4 border-t border-border dark:border-dark-700 flex justify-between items-center">
                      <div className="flex items-center gap-2 text-muted-foreground dark:text-gray-400">
                        <Icon icon="fa-solid:clock" />
                        <span className="text-sm">
                          {new Date(signal.createdAt).toLocaleString('en-US', {
                            hour: '2-digit',
                            minute: '2-digit',
                            month: 'short',
                            day: 'numeric'
                          })}
                        </span>
                      </div>
                    </div>

                    {signal.description && (
                      <div className="mt-4 p-3 bg-primary/5 rounded-lg border border-primary/10 dark:bg-primary/10">
                        <p className="text-sm text-foreground/80 italic dark:text-gray-300">&quot;{signal.description}&quot;</p>
                      </div>
                    )}
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
    
   <div className="divider" />
      <Disclaimer/>

        </div>
      </main>

      <Footer />
    </div>
  );
}

export const metadata = {

    title: 'Free Live Trading Signals - Updated Every 8 Hours',
    description: 'Access free real-time AI-generated trading signals for crypto . Includes entry price, take profit levels, stop loss, and confidence score. No signup required.',

};

